# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UpdatedGUI.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QFrame,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStackedWidget, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(798, 513)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLikes = QAction(MainWindow)
        self.actionLikes.setObjectName(u"actionLikes")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 0, 791, 451))
        self.stackedWidget.setFrameShadow(QFrame.Shadow.Raised)
        self.MainPage = QWidget()
        self.MainPage.setObjectName(u"MainPage")
        self.CurrTime = QLabel(self.MainPage)
        self.CurrTime.setObjectName(u"CurrTime")
        self.CurrTime.setGeometry(QRect(290, 10, 221, 41))
        self.CurrTime.setFrameShape(QFrame.Shape.WinPanel)
        self.CurrTime.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModifyButt = QPushButton(self.MainPage)
        self.ModifyButt.setObjectName(u"ModifyButt")
        self.ModifyButt.setGeometry(QRect(300, 370, 211, 41))
        self.TempTitle1 = QLabel(self.MainPage)
        self.TempTitle1.setObjectName(u"TempTitle1")
        self.TempTitle1.setGeometry(QRect(60, 80, 111, 16))
        self.HumidityTitle1 = QLabel(self.MainPage)
        self.HumidityTitle1.setObjectName(u"HumidityTitle1")
        self.HumidityTitle1.setGeometry(QRect(60, 190, 58, 16))
        # self.LightTitle1 = QLabel(self.MainPage)
        # self.LightTitle1.setObjectName(u"LightTitle1")
        # self.LightTitle1.setGeometry(QRect(60, 310, 81, 16))
        # self.SoundTitle1 = QLabel(self.MainPage)
        # self.SoundTitle1.setObjectName(u"SoundTitle1")
        # self.SoundTitle1.setGeometry(QRect(60, 380, 81, 16))
        self.frame = QFrame(self.MainPage)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(500, 70, 21, 281))
        self.frame.setAutoFillBackground(False)
        self.frame.setFrameShape(QFrame.Shape.VLine)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.InTemp = QLabel(self.MainPage)
        self.InTemp.setObjectName(u"InTemp")
        self.InTemp.setGeometry(QRect(60, 110, 231, 71))
        self.InTemp.setFrameShape(QFrame.Shape.Box)
        self.InTemp.setFrameShadow(QFrame.Shadow.Raised)
        self.InTemp.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.InTemp.setWordWrap(False)
        self.InHumid = QLabel(self.MainPage)
        self.InHumid.setObjectName(u"InHumid")
        self.InHumid.setGeometry(QRect(60, 210, 231, 71))
        self.InHumid.setFrameShape(QFrame.Shape.Box)
        self.InHumid.setFrameShadow(QFrame.Shadow.Raised)
        self.InHumid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.InLight = QLabel(self.MainPage)
        # self.InLight.setObjectName(u"InLight")
        # self.InLight.setGeometry(QRect(60, 330, 131, 41))
        # self.InLight.setFrameShape(QFrame.Shape.Box)
        # self.InLight.setFrameShadow(QFrame.Shadow.Raised)
        # self.InLight.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.InSound = QLabel(self.MainPage)
        # self.InSound.setObjectName(u"InSound")
        # self.InSound.setGeometry(QRect(60, 400, 131, 41))
        # self.InSound.setFrameShape(QFrame.Shape.Box)
        # self.InSound.setFrameShadow(QFrame.Shadow.Raised)
        # self.InSound.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.SoundTitle2 = QLabel(self.MainPage)
        # self.SoundTitle2.setObjectName(u"SoundTitle2")
        # self.SoundTitle2.setGeometry(QRect(680, 380, 81, 16))
        self.HumdityTitle2 = QLabel(self.MainPage)
        self.HumdityTitle2.setObjectName(u"HumdityTitle2")
        self.HumdityTitle2.setGeometry(QRect(700, 190, 58, 16))
        self.TempTitle2 = QLabel(self.MainPage)
        self.TempTitle2.setObjectName(u"TempTitle2")
        self.TempTitle2.setGeometry(QRect(650, 80, 111, 16))
        # self.LightTitle2 = QLabel(self.MainPage)
        # self.LightTitle2.setObjectName(u"LightTitle2")
        # self.LightTitle2.setGeometry(QRect(670, 310, 81, 16))
        # self.label_14 = QLabel(self.MainPage)
        # self.label_14.setObjectName(u"label_14")
        # self.label_14.setGeometry(QRect(620, 400, 131, 41))
        # self.label_14.setFrameShape(QFrame.Shape.Box)
        # self.label_14.setFrameShadow(QFrame.Shadow.Raised)
        # self.label_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.OuTemp = QLabel(self.MainPage)
        self.OuTemp.setObjectName(u"OuTemp")
        self.OuTemp.setGeometry(QRect(520, 110, 231, 71))
        self.OuTemp.setFrameShape(QFrame.Shape.Box)
        self.OuTemp.setFrameShadow(QFrame.Shadow.Raised)
        self.OuTemp.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.OutHumid = QLabel(self.MainPage)
        self.OutHumid.setObjectName(u"OutHumid")
        self.OutHumid.setGeometry(QRect(520, 210, 231, 71))
        self.OutHumid.setFrameShape(QFrame.Shape.Box)
        self.OutHumid.setFrameShadow(QFrame.Shadow.Raised)
        self.OutHumid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        # self.OutLight = QLabel(self.MainPage)
        # self.OutLight.setObjectName(u"OutLight")
        # self.OutLight.setGeometry(QRect(620, 330, 131, 41))
        # self.OutLight.setFrameShape(QFrame.Shape.Box)
        # self.OutLight.setFrameShadow(QFrame.Shadow.Raised)
        # self.OutLight.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.InTitle = QLabel(self.MainPage)
        self.InTitle.setObjectName(u"InTitle")
        self.InTitle.setGeometry(QRect(60, 20, 141, 41))
        font = QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.InTitle.setFont(font)
        self.InTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.OutTitle = QLabel(self.MainPage)
        self.OutTitle.setObjectName(u"OutTitle")
        self.OutTitle.setGeometry(QRect(590, 20, 171, 41))
        self.OutTitle.setFont(font)
        self.OutTitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.HLine = QFrame(self.MainPage)
        self.HLine.setObjectName(u"HLine")
        self.HLine.setGeometry(QRect(20, 40, 761, 51))
        self.HLine.setFrameShape(QFrame.Shape.HLine)
        self.HLine.setFrameShadow(QFrame.Shadow.Raised)
        self.Smoke = QLabel(self.MainPage)
        self.Smoke.setObjectName(u"Smoke")
        self.Smoke.setGeometry(QRect(330, 170, 151, 51))
        self.Smoke.setFrameShape(QFrame.Shape.Box)
        self.Smoke.setFrameShadow(QFrame.Shadow.Raised)
        self.Smoke.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.Smoke.setWordWrap(False)
        self.frame_2 = QFrame(self.MainPage)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(290, 80, 21, 281))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setFrameShape(QFrame.Shape.VLine)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.AutoMode = QCheckBox(self.MainPage)
        self.AutoMode.setObjectName(u"AutoMode")
        self.AutoMode.setEnabled(True)
        self.AutoMode.setGeometry(QRect(350, 420, 101, 21))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setKerning(True)
        self.AutoMode.setFont(font1)
        self.AutoMode.setChecked(False)
        self.CO2 = QLabel(self.MainPage)
        self.CO2.setObjectName(u"CO2")
        self.CO2.setGeometry(QRect(330, 270, 151, 51))
        self.CO2.setFrameShape(QFrame.Shape.Box)
        self.CO2.setFrameShadow(QFrame.Shadow.Raised)
        self.CO2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.CO2.setWordWrap(False)
        self.TempTitle1_2 = QLabel(self.MainPage)
        self.TempTitle1_2.setObjectName(u"TempTitle1_2")
        self.TempTitle1_2.setGeometry(QRect(380, 150, 111, 16))
        font2 = QFont()
        font2.setPointSize(14)
        self.TempTitle1_2.setFont(font2)
        self.TempTitle1_3 = QLabel(self.MainPage)
        self.TempTitle1_3.setObjectName(u"TempTitle1_3")
        self.TempTitle1_3.setGeometry(QRect(390, 250, 31, 16))
        self.TempTitle1_3.setFont(font2)
        self.stackedWidget.addWidget(self.MainPage)
        self.ModifyPage = QWidget()
        self.ModifyPage.setObjectName(u"ModifyPage")
        self.DoneModButt = QPushButton(self.ModifyPage)
        self.DoneModButt.setObjectName(u"DoneModButt")
        self.DoneModButt.setGeometry(QRect(410, 340, 131, 41))
        self.TempModifyTo = QDoubleSpinBox(self.ModifyPage)
        self.TempModifyTo.setObjectName(u"TempModifyTo")
        self.TempModifyTo.setGeometry(QRect(240, 250, 91, 21))
        self.HumidModifyTo = QDoubleSpinBox(self.ModifyPage)
        self.HumidModifyTo.setObjectName(u"HumidModifyTo")
        self.HumidModifyTo.setGeometry(QRect(570, 250, 101, 21))
        self.TempTitle3 = QLabel(self.ModifyPage)
        self.TempTitle3.setObjectName(u"TempTitle3")
        self.TempTitle3.setGeometry(QRect(170, 140, 111, 16))
        self.HumidityTitle3 = QLabel(self.ModifyPage)
        self.HumidityTitle3.setObjectName(u"HumidityTitle3")
        self.HumidityTitle3.setGeometry(QRect(520, 140, 58, 16))
        self.CancelModButt = QPushButton(self.ModifyPage)
        self.CancelModButt.setObjectName(u"CancelModButt")
        self.CancelModButt.setGeometry(QRect(220, 340, 141, 41))
        self.ModTemp = QLabel(self.ModifyPage)
        self.ModTemp.setObjectName(u"ModTemp")
        self.ModTemp.setGeometry(QRect(100, 170, 231, 71))
        self.ModTemp.setFrameShape(QFrame.Shape.Box)
        self.ModTemp.setFrameShadow(QFrame.Shadow.Raised)
        self.ModTemp.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModTemp.setWordWrap(False)
        self.ModHumid = QLabel(self.ModifyPage)
        self.ModHumid.setObjectName(u"ModHumid")
        self.ModHumid.setGeometry(QRect(440, 170, 231, 71))
        self.ModHumid.setFrameShape(QFrame.Shape.Box)
        self.ModHumid.setFrameShadow(QFrame.Shadow.Raised)
        self.ModHumid.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ModHumid.setWordWrap(False)
        self.TempModifyFrom = QDoubleSpinBox(self.ModifyPage)
        self.TempModifyFrom.setObjectName(u"TempModifyFrom")
        self.TempModifyFrom.setGeometry(QRect(100, 250, 91, 21))
        self.HumidModifyFrom = QDoubleSpinBox(self.ModifyPage)
        self.HumidModifyFrom.setObjectName(u"HumidModifyFrom")
        self.HumidModifyFrom.setGeometry(QRect(440, 250, 91, 21))
        self.ModNote = QLabel(self.ModifyPage)
        self.ModNote.setObjectName(u"ModNote")
        self.ModNote.setGeometry(QRect(450, 420, 351, 20))
        self.stackedWidget.addWidget(self.ModifyPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 798, 24))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionLikes)
        self.menuEdit.addAction(self.actionPaste)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(statustip)
        self.actionNew.setStatusTip(QCoreApplication.translate("MainWindow", u"Create a new file", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"save a file", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Return", None))
#endif // QT_CONFIG(shortcut)
        self.actionLikes.setText(QCoreApplication.translate("MainWindow", u"Add Current Setting", None))
#if QT_CONFIG(shortcut)
        self.actionLikes.setShortcut(QCoreApplication.translate("MainWindow", u"Backspace, Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Load Saved Settings", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.CurrTime.setText(QCoreApplication.translate("MainWindow", u"Current Time: 4:05 PM", None))
        self.ModifyButt.setText(QCoreApplication.translate("MainWindow", u"Modify", None))
        self.TempTitle1.setText(QCoreApplication.translate("MainWindow", u"Temperature (\u00b0F)", None))
        self.HumidityTitle1.setText(QCoreApplication.translate("MainWindow", u"Humidity", None))
        #self.LightTitle1.setText(QCoreApplication.translate("MainWindow", u"Light (lumen)", None))
        #self.SoundTitle1.setText(QCoreApplication.translate("MainWindow", u"Sound (dB)", None))
        self.InTemp.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.InHumid.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        #self.InLight.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        #self.InSound.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        #self.SoundTitle2.setText(QCoreApplication.translate("MainWindow", u"Sound (dB)", None))
        self.HumdityTitle2.setText(QCoreApplication.translate("MainWindow", u"Humidity", None))
        self.TempTitle2.setText(QCoreApplication.translate("MainWindow", u"Temperature (\u00b0F)", None))
        #self.LightTitle2.setText(QCoreApplication.translate("MainWindow", u"Light (lumen)", None))
        self.OuTemp.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.OutHumid.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        #self.OutLight.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.InTitle.setText(QCoreApplication.translate("MainWindow", u"Indoor", None))
        self.OutTitle.setText(QCoreApplication.translate("MainWindow", u"Outdoor", None))
        self.Smoke.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.AutoMode.setText(QCoreApplication.translate("MainWindow", u"Auto Mode", None))
        self.CO2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.TempTitle1_2.setText(QCoreApplication.translate("MainWindow", u"Smoke", None))
        self.TempTitle1_3.setText(QCoreApplication.translate("MainWindow", u"CO2", None))
        self.DoneModButt.setText(QCoreApplication.translate("MainWindow", u"Done", None))
        self.TempTitle3.setText(QCoreApplication.translate("MainWindow", u"Temperature (\u00b0F)", None))
        self.HumidityTitle3.setText(QCoreApplication.translate("MainWindow", u"Humidity", None))
        self.CancelModButt.setText(QCoreApplication.translate("MainWindow", u"Cancel", None))
        self.ModTemp.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.ModHumid.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.ModNote.setText(QCoreApplication.translate("MainWindow", u"Note: Settings will only be valid when Auto Mode is OFF", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
    # retranslateUi

